disabled_rules:
- trailing_newline
- opening_brace
- empty_count
- comma
- colon
- force_cast
- type_name
- trailing_semicolon
- force_try
- function_body_length
- nesting
- variable_name
- operator_whitespace
- control_statement
- line_length
- return_arrow_whitespace
- trailing_whitespace
- closing_brace
- statement_position
- type_body_length
- todo
- file_length
- leading_whitespace
- redundant_optional_initialization
- cyclomatic_complexity
- unused_optional_binding
- void_return 
- implicit_getter
- unused_closure_parameter
- mark 
- notification_center_detachment
- for_where
- vertical_whitespace
- empty_parameters
- discarded_notification_center_observer
- class_delegate_protocol
- syntactic_sugar 
- function_parameter_count 
- trailing_comma 
- weak_delegate 
- redundant_string_enum_value 
- unused_enumerated
- empty_enum_arguments
- shorthand_operator
- empty_parentheses_with_trailing_closure
- closure_parameter_position
- redundant_discardable_let
- large_tuple
- vertical_parameter_alignment
included:
- FirstStage
